# InfluxDB container
influxdb:
  restart: always
  volumes:
    # Keeping data on the host
    - "/var/influxdb/data:/data"

# Grafana container
grafana:
  restart: always
  ports:
    - "3000:3000"
  volumes:
    # Editable dashboards
    - "/usr/lib/grafana/dashboards:/usr/lib/grafana/dashboards"

# Ontrack container
ontrack:
  restart: always
  image: nemerosa/ontrack:${ONTRACK_VERSION}
  environment:
      PROFILE: prod
  volumes:
    - "/var/ontrack/conf:/var/ontrack/conf"
    - "/var/ontrack/data:/var/ontrack/data"
      # Using the random source from the host
    - "/dev/urandom:/dev/random"
  ports:
    - "443:443"
  links:
    - "postgresql:postgresql"

# Postgresql database
postgresql:
  image: postgres:9.5.2
  environment:
    POSTGRES_DB      : ontrack
    POSTGRES_USER    : ontrack
    POSTGRES_PASSWORD: ${ONTRACK_POSTGRES_PASSWORD}
  volumes:
    - "/var/lib/postgresql/data:/var/lib/postgresql/data"
  ports:
    - "5432:5432"
