# InfluxDB container
influxdb:
  # Makes all ports accessible on the host for testing
  ports:
    - "8083"
    - "8086"

# Grafana
grafana:
  ports:
    - "3000"

# Ontrack container
ontrack:
  environment:
      PROFILE: acceptance
  volumes:
    - "./ci/ontrack:/var/ontrack/conf"
    # Better startup performances in CI and DO, do not use in Prod
    - "/dev/urandom:/dev/random"
  ports:
    - "443"
  links:
    - "postgresql:postgresql"

# Postgresql database
postgresql:
  image: postgres:9.5.2
  environment:
    POSTGRES_DB      : ontrack
    POSTGRES_USER    : ontrack
    POSTGRES_PASSWORD: ontrack
  ports:
    - "5432"
