# InfluxDB container
influxdb:
  # Makes all ports accessible on the host for testing
  ports:
    - "8083:8083"

# Grafana container
grafana:
  ports:
    - "3000:3000"

# Ontrack container
ontrack:
  image: nemerosa/ontrack:${ONTRACK_VERSION}
  environment:
      PROFILE: acceptance
  volumes:
    # The /var/ontrack/conf on the DO machine is filled in from gradle/compose/ci/ontrack in the doEnv task
    - "/var/ontrack/conf:/var/ontrack/conf"
    # Better startup performances in CI and DO, do not use in Prod
    - "/dev/urandom:/dev/random"
  ports:
    - "443:443"
  links:
    - "postgresql:postgresql"

# Postgresql database
postgresql:
  image: postgres:9.5.2
  environment:
    POSTGRES_DB      : ontrack
    POSTGRES_USER    : ontrack
    POSTGRES_PASSWORD: ontrack
  ports:
    - "5432"
