ontrack:
  migration:
    cleanup: true
    h2:
      url: "jdbc:h2:./data;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DEFRAG_ALWAYS=TRUE"
      username: ontrack
      password: ontrack
    postgresql:
      url: "jdbc:postgresql://postgresql/ontrack"
      username: ontrack
      password: ontrack
