# Application properties

# Flyway configuration
# See RepositoryConfig for general Flyway configuration
flyway:
  baseline-on-migrate: true

# Spring configuration
spring:
  # Default database connection
  datasource:
    url: "jdbc:postgresql://postgresql/ontrack"
    username: ontrack
    password: ontrack
  # Default profile
  profiles:
    default: prod
  # AOP configuration
  aop:
    proxyTargetClass: true


# Management
management:
  context-path: "/manage"

# Security

# No security by default for the application end points
security:
  basic:
    enabled: false

# General information
# The version information is generated in /application.properties by the build
info:
  app:
    name: Ontrack
    description: Continuous Delivery Traceability and Monitoring

# Session configuration
# This can be overridden at installation level
#server:
#  session:
#    # One hour for the session
#    timeout: 3600
#    cookie:
#      max-age: 3600
