package net.nemerosa.ontrack.common;

/**
 * List of cache entries
 */
public interface Caches {

    String SETTINGS = "SETTINGS";

    String PROJECTS = "PROJECTS";

    String BRANCHES = "BRANCHES";

    // TODO PREDEFINED_PROMOTION_LEVELS
    // TODO PREDEFINED_VALIDATION_STAMPS
    // TODO STORAGE
    // TODO PROMOTION_LEVELS
    // TODO VALIDATION_STAMPS
    // TODO BUILDS
    // TODO PROMOTION_RUNS
    // TODO VALIDATION_RUNS
    // TODO VALIDATION_RUN_STATUSES
    // TODO BRANCH_TEMPLATE_DEFINITIONS
    // TODO BRANCH_TEMPLATE_DEFINITION_PARAMS
    // TODO BRANCH_TEMPLATE_INSTANCES
    // TODO BRANCH_TEMPLATE_INSTANCE_PARAMS
    // TODO ENTITY_DATA
    // TODO PROPERTIES
    // TODO SHARED_BUILD_FILTERS
    // TODO BUILD_LINKS
    // TODO EVENTS
    // TODO ACCOUNTS
    // TODO ACCOUNT_GROUPS
    // TODO ACCOUNT_GROUP_LINK
    // TODO ACCOUNT_GROUP_MAPPING
    // TODO GLOBAL_AUTHORIZATIONS
    // TODO GROUP_GLOBAL_AUTHORIZATIONS
    // TODO GROUP_PROJECT_AUTHORIZATIONS
    // TODO PROJECT_AUTHORIZATIONS
    // TODO PREFERENCES
    // TODO BUILD_FILTERS

}
